In [1]:
import numpy as np

In [2]:
def period_v(npa, dmax):
    for a in range(1, dmax // 2):
        shift = np.roll(npa, a)
        if np.array_equal(npa[a:], shift[a:]):
            return a
    return None

In [9]:
def calc_v(p, cmax, dmax, display):
    prev = np.array([1 for a in range(dmax)])
    cols = []
    for a in range(cmax):
        if display != 0:
            print(period_v(prev, dmax), "\t", prev[:display])
        cols.append(prev)
        prev = np.cumsum(prev) % p
    return cols

In [34]:
def cong_seqs(cols, n):
    seqs = set()
    for a in range(len(cols)):
        period = period_v(cols[a], len(cols[a]))
        if period == None:
            period = len(cols[a])
        for b in range(min(len(cols[a]) - n, period)):
            seqs.add(tuple(cols[a][b:b+n]))
    return seqs

In [48]:
def p_unique_seqs(cols, n):
    res = len(cong_seqs(cols, n))
    print("Unique sequences of n =", n, ":", res)
    return res

In [41]:
cols = calc_v(7, 1000, 1000, 0)
for a in range(2, 10):
    p_unique_seqs(cols, a)

Unique sequences of n = 2 : 49
Unique sequences of n = 3 : 253
Unique sequences of n = 4 : 403
Unique sequences of n = 5 : 589
Unique sequences of n = 6 : 811
Unique sequences of n = 7 : 1069
Unique sequences of n = 8 : 1363
Unique sequences of n = 9 : 1812


In [42]:
cols = calc_v(2, 1000, 1000, 0)
for a in range(2, 10):
    p_unique_seqs(cols, a)

Unique sequences of n = 2 : 4
Unique sequences of n = 3 : 8
Unique sequences of n = 4 : 14
Unique sequences of n = 5 : 22
Unique sequences of n = 6 : 32
Unique sequences of n = 7 : 44
Unique sequences of n = 8 : 58
Unique sequences of n = 9 : 74


In [46]:
cols = calc_v(3, 1000, 1000, 0)
c_uniques = []
for a in range(1, 50):
    c_uniques.append(p_unique_seqs(cols, a))

Unique sequences of n = 1 : 3
Unique sequences of n = 2 : 9
Unique sequences of n = 3 : 25
Unique sequences of n = 4 : 43
Unique sequences of n = 5 : 71
Unique sequences of n = 6 : 109
Unique sequences of n = 7 : 157
Unique sequences of n = 8 : 207
Unique sequences of n = 9 : 259
Unique sequences of n = 10 : 313
Unique sequences of n = 11 : 377
Unique sequences of n = 12 : 451
Unique sequences of n = 13 : 535
Unique sequences of n = 14 : 629
Unique sequences of n = 15 : 733
Unique sequences of n = 16 : 847
Unique sequences of n = 17 : 971
Unique sequences of n = 18 : 1105
Unique sequences of n = 19 : 1249
Unique sequences of n = 20 : 1395
Unique sequences of n = 21 : 1543
Unique sequences of n = 22 : 1693
Unique sequences of n = 23 : 1845
Unique sequences of n = 24 : 1999
Unique sequences of n = 25 : 2155
Unique sequences of n = 26 : 2313
Unique sequences of n = 27 : 2473
Unique sequences of n = 28 : 2635
Unique sequences of n = 29 : 2807
Unique sequences of n = 30 : 2989
Unique sequen

In [64]:
c_uniques = np.array(c_uniques)
print(c_uniques)
print(np.diff(c_uniques))
print(np.diff(np.diff(c_uniques)))

[   3    9   25   43   71  109  157  207  259  313  377  451  535  629
  733  847  971 1105 1249 1395 1543 1693 1845 1999 2155 2313 2473 2635
 2807 2989 3181 3383 3595 3817 4049 4291 4543 4805 5077 5359 5651 5953
 6265 6587 6919 7261 7613 7975 8347]
[  6  16  18  28  38  48  50  52  54  64  74  84  94 104 114 124 134 144
 146 148 150 152 154 156 158 160 162 172 182 192 202 212 222 232 242 252
 262 272 282 292 302 312 322 332 342 352 362 372]
[10  2 10 10 10  2  2  2 10 10 10 10 10 10 10 10 10  2  2  2  2  2  2  2
  2  2 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]


In [65]:
def get_patterns(p, n):
    patterns = [[1, p - 1]] if p > 2 else [[1]]
    for _ in range(n - 1):
        pat = [1]
        while True:
            for x in patterns[-1][1:]:
                pat.append((x - pat[-1]) % p)
            if pat[-1] == 0:
                break
            pat.append((1 - pat[-1]) % p)
        
        patterns.append(pat)

    return patterns

In [66]:
def count_substrings(patterns, n):
    patterns = ["".join(map(str, pat)) for pat in patterns]
    
    cs = [0]
    for n in range(1, n):
        ss = set()
        for pat in patterns:
            rep = (n // len(pat) + 2) * pat
            for i in range(len(pat)):
                ss.add(rep[i:i + n])
    
        cs.append(len(ss))
    
    return cs

In [77]:
csubs = count_substrings(get_patterns(p=3, n=1000), n=101)

In [78]:
print(csubs)
print(np.diff(csubs))
print(np.diff(np.diff(csubs)))

[0, 3, 9, 25, 43, 71, 109, 157, 207, 259, 313, 377, 451, 535, 629, 733, 847, 971, 1105, 1249, 1395, 1543, 1693, 1845, 1999, 2155, 2313, 2473, 2635, 2807, 2989, 3181, 3383, 3595, 3817, 4049, 4291, 4543, 4805, 5077, 5359, 5651, 5953, 6265, 6587, 6919, 7261, 7613, 7975, 8347, 8729, 9121, 9523, 9935, 10357, 10789, 11223, 11659, 12097, 12537, 12979, 13423, 13869, 14317, 14767, 15219, 15673, 16129, 16587, 17047, 17509, 17973, 18439, 18907, 19377, 19849, 20323, 20799, 21277, 21757, 22239, 22723, 23209, 23705, 24211, 24727, 25253, 25789, 26335, 26891, 27457, 28033, 28619, 29215, 29821, 30437, 31063, 31699, 32345, 33001, 33667]
[  3   6  16  18  28  38  48  50  52  54  64  74  84  94 104 114 124 134
 144 146 148 150 152 154 156 158 160 162 172 182 192 202 212 222 232 242
 252 262 272 282 292 302 312 322 332 342 352 362 372 382 392 402 412 422
 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466
 468 470 472 474 476 478 480 482 484 486 496 506 516 526 536 546 556 566
 576 586

In [79]:
csubst = np.array([csubs[1], csubs[4], csubs[10], csubs[28], csubs[100]])
print(csubst)
print(np.diff(csubst))
print(np.diff(np.diff(csubst)))
print(np.diff(np.diff(np.diff(csubst))))

[    3    43   313  2635 33667]
[   40   270  2322 31032]
[  230  2052 28710]
[ 1822 26658]


In [84]:
cols = calc_v(3, 100, 100, 0)
print(np.array(sorted(list(cong_seqs(cols, 3)))))

[[0 0 0]
 [0 0 1]
 [0 0 2]
 [0 1 0]
 [0 1 1]
 [0 1 2]
 [0 2 0]
 [0 2 1]
 [0 2 2]
 [1 0 0]
 [1 0 1]
 [1 0 2]
 [1 1 0]
 [1 1 1]
 [1 1 2]
 [1 2 0]
 [1 2 2]
 [2 0 0]
 [2 0 1]
 [2 0 2]
 [2 1 0]
 [2 1 1]
 [2 2 0]
 [2 2 1]
 [2 2 2]]
